# Generated by Django 4.2.4 on 2023-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=100000),
        ),
    ]
