# Generated by Django 4.2.4 on 2023-09-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulation', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
