# Generated by Django 4.2.4 on 2023-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulation', '0004_alter_transaction_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
