# Generated by Django 4.2.4 on 2023-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_simulation', '0005_alter_stockdata_close_price_alter_stockdata_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=10),
        ),
    ]
